package com.example.coding.sort.leetcode.easy;

/**
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Return the letter that was added to t.
 *
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 */
public class FindTheDifference {

  public static char findTheDifference(String s, String t) {
    int[] mainIntArray = new int[26];
    char result = ' ';

    for (int i = 0; i < s.length(); i++) {
      char currentChar = s.charAt(i);
      mainIntArray[currentChar - 'a'] ++;
    }

    for (int i = 0; i < t.length(); i++) {
      char currentChar = t.charAt(i);

      if (mainIntArray[currentChar - 'a'] == 0) {
        result =  currentChar;
        break;
      }
    }
    return result;
  }

  public static void main(String[] args) {
    String s = "abcd";
    String t = "bacde";

    System.out.println(findTheDifference(s, t));
  }
}
